import { validateDemandSubmission } from './demand-capture.ts'
function eq(a: unknown,b: unknown){if(JSON.stringify(a)!==JSON.stringify(b))throw new Error(`Expected ${JSON.stringify(b)}, got ${JSON.stringify(a)}`)}
function throws(fn:()=>unknown,code:string){try{fn()}catch(e){eq(e instanceof Error?e.message:String(e),code);return}throw new Error(`Expected ${code}`)}
const base={name:'Pessoa Adversarial',whatsapp:'(48) 99999-1234',email:'pessoa@example.com',brand:'brand-a',service_id:'11111111-1111-4111-8111-111111111111',desired_date:'2030-01-02',desired_period:'MANHA',consent_contact:true,consent_text_version:'v1'}
const now=new Date('2026-08-22T12:00:00Z')
Deno.test('adversarial demand: malformed and missing required fields fail server validation',()=>{throws(()=>validateDemandSubmission(null,['brand-a'],now),'INVALID_REQUEST');throws(()=>validateDemandSubmission({...base,name:undefined},['brand-a'],now),'NAME_INVALID');throws(()=>validateDemandSubmission({...base,email:123},['brand-a'],now),'EMAIL_INVALID')})
Deno.test('adversarial demand: brand and service are allowlisted/typed',()=>{throws(()=>validateDemandSubmission({...base,brand:'brand-b'},['brand-a'],now),'BRAND_INVALID');throws(()=>validateDemandSubmission({...base,service_id:'1 OR 1=1'},['brand-a'],now),'SERVICE_INVALID')})
Deno.test('adversarial demand: phone date period and consent fail server validation',()=>{throws(()=>validateDemandSubmission({...base,whatsapp:'123'},['brand-a'],now),'WHATSAPP_INVALID');throws(()=>validateDemandSubmission({...base,desired_date:'02/01/2030'},['brand-a'],now),'DESIRED_DATE_INVALID');throws(()=>validateDemandSubmission({...base,desired_period:'QUALQUER'},['brand-a'],now),'DESIRED_PERIOD_INVALID');throws(()=>validateDemandSubmission({...base,consent_contact:'true'},['brand-a'],now),'CONSENT_REQUIRED')})
Deno.test('adversarial demand: extra client fields cannot enter persistence contract',()=>{const r=validateDemandSubmission({...base,price:1,resource_id:'00000000-0000-0000-0000-000000000000',admin_status:'CONVERTED'},['brand-a'],now) as unknown as Record<string,unknown>;eq('price' in r,false);eq('resource_id' in r,false);eq('admin_status' in r,false)})
