import { useEffect, useMemo, useState } from 'react'
import {
  bindCheckoutCustomer,
  clearCheckoutPackage,
  listCheckoutPackages,
  loadCheckoutContext,
  selectCheckoutPackage,
  submitBookingCheckout,
  type AppointmentCheckoutResult,
  type BookingField,
  type CheckoutContext,
  type CheckoutHold,
  type CheckoutPackage,
  type ServiceAnswer,
} from './bookingApi'
import { applyCheckoutCoupon, clearCheckoutCoupon, loadCheckoutCoupon, type CheckoutCouponState } from './checkoutCouponApi'

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })
const dateTime = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short', timeZone: 'America/Sao_Paulo' })
type CheckoutResult = AppointmentCheckoutResult & { pre_reservation?: boolean; pre_reservation_id?: string; pre_reservation_expires_at?: string | null; pre_reservation_email_sent?: boolean }
function numeric(value: number | string | undefined): number { const parsed=Number(value??0);return Number.isFinite(parsed)?parsed:0 }
function digits(value:string):string{return value.replace(/\D/g,'')}
function deadline(value:string|null|undefined):string{if(!value)return'48 horas';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?'48 horas':dateTime.format(parsed)}
function readableError(error:unknown):string{
  const raw=error instanceof Error?error.message:'CHECKOUT_FAILED'
  const known:Array<[string,string]>=[
    ['CHECKOUT_HOLD_NOT_ACTIVE','O tempo para concluir a reserva terminou. Escolha o horário novamente.'],
    ['HOLD_EXPIRED','O tempo para concluir a reserva terminou. Escolha o horário novamente.'],
    ['MAX_ACTIVE_PREBOOKS_REACHED','Você já atingiu o limite de pré-reservas ativas. Confirme ou aguarde a expiração de uma delas para escolher outro horário.'],
    ['INVALID_COUPON','Este cupom não é válido para esta reserva.'],
    ['COUPON_USAGE_LIMIT_REACHED','Este cupom atingiu o limite de utilizações.'],
    ['COUPON_CUSTOMER_USAGE_LIMIT_REACHED','Você já utilizou este cupom o número máximo de vezes permitido.'],
    ['COUPON_CUSTOMER_MISMATCH','Este cupom é destinado a outro cliente.'],
    ['COUPON_PACKAGE_POLICY_REQUIRES_DECISION','Remova o pacote de horas antes de aplicar um cupom.'],
    ['CUSTOMER_NAME_INVALID','Informe seu nome completo.'],['CUSTOMER_EMAIL_INVALID','Informe um e-mail válido.'],['CUSTOMER_PHONE_INVALID','Informe um WhatsApp válido.'],['CUSTOMER_TAX_ID_INVALID','Informe um CPF ou CNPJ válido.'],
    ['CUSTOMER_IDENTITY_AMBIGUOUS','Encontramos mais de um cadastro com estes dados. Fale com a equipe para continuar.'],['CUSTOMER_IDENTITY_CONFLICT','Os dados informados não correspondem ao cadastro já vinculado.'],
    ['ONLINE_BOOKING_NOT_AVAILABLE','Não foi possível concluir esta reserva online. Entre em contato conosco para agendar.'],['FREE_VISIT_ACTIVE_LIMIT_REACHED','Você já possui uma visita agendada. Entre em contato conosco se precisar alterar o horário.'],
    ['REQUIRED_SERVICE_FIELDS_MISSING','Preencha todos os campos obrigatórios do serviço.'],['INVALID_SERVICE_ANSWER_VALUE','Revise as informações específicas do serviço.'],['TERMS_NOT_ACCEPTED','Aceite todos os termos para continuar.'],['TERMS_CONFIGURATION_MISSING','Os termos deste serviço ainda não estão configurados.'],['HOUR_PACKAGE_INSUFFICIENT_BALANCE','Este pacote não possui saldo suficiente para a reserva.'],['RATE_LIMITED','Muitas tentativas em sequência. Tente novamente em alguns minutos.'],
  ]
  return known.find(([key])=>raw.includes(key))?.[1]??'Não foi possível concluir esta etapa. Revise os dados e tente novamente.'
}
function selectOptions(field:BookingField):Array<{value:string;label:string}>{if(!Array.isArray(field.options))return[];return field.options.flatMap(item=>{if(typeof item==='string')return[{value:item,label:item}];if(item&&typeof item==='object'){const row=item as Record<string,unknown>;const value=typeof row.value==='string'?row.value:'';const label=typeof row.label==='string'?row.label:value;return value?[{value,label}]:[]}return[]})}
function FieldInput({field,value,onChange}:{field:BookingField;value:string|number|boolean|null|undefined;onChange:(value:string|number|boolean|null)=>void}){
  if(field.field_type==='BOOLEAN')return <label className="checkout-checkbox"><input type="checkbox" checked={value===true} onChange={e=>onChange(e.target.checked)}/><span>{field.label}{field.is_required?' *':''}</span></label>
  if(field.field_type==='SELECT')return <label>{field.label}{field.is_required?' *':''}<select value={typeof value==='string'?value:''} onChange={e=>onChange(e.target.value||null)} required={field.is_required}><option value="">Selecione</option>{selectOptions(field).map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>{field.help_text?<small>{field.help_text}</small>:null}</label>
  if(field.field_type==='TEXTAREA')return <label>{field.label}{field.is_required?' *':''}<textarea value={typeof value==='string'?value:''} placeholder={field.placeholder??undefined} onChange={e=>onChange(e.target.value)} required={field.is_required}/>{field.help_text?<small>{field.help_text}</small>:null}</label>
  const type=field.field_type==='DATE'?'date':field.field_type==='NUMBER'?'number':'text'
  return <label>{field.label}{field.is_required?' *':''}<input type={type} value={typeof value==='boolean'||value==null?'':String(value)} placeholder={field.placeholder??undefined} required={field.is_required} onChange={e=>onChange(field.field_type==='NUMBER'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/>{field.help_text?<small>{field.help_text}</small>:null}</label>
}

export function BookingCheckout({hold}:{hold:CheckoutHold}){
  const[context,setContext]=useState<CheckoutContext|null>(null);const[coupon,setCoupon]=useState<CheckoutCouponState|null>(null);const[couponCode,setCouponCode]=useState('');const[couponBusy,setCouponBusy]=useState(false);const[priceConfirmed,setPriceConfirmed]=useState(false)
  const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[name,setName]=useState('');const[email,setEmail]=useState('');const[phone,setPhone]=useState('');const[taxId,setTaxId]=useState('');const[binding,setBinding]=useState(false);const[customerBound,setCustomerBound]=useState(false);const[packages,setPackages]=useState<CheckoutPackage[]>([]);const[packageId,setPackageId]=useState('');const[packageBusy,setPackageBusy]=useState(false);const[answers,setAnswers]=useState<Record<string,string|number|boolean|null>>({});const[acceptedTerms,setAcceptedTerms]=useState<Record<string,boolean>>({});const[submitting,setSubmitting]=useState(false);const[result,setResult]=useState<CheckoutResult|null>(null)
  useEffect(()=>{let active=true;Promise.all([loadCheckoutContext(hold.checkout_hold_token),loadCheckoutCoupon(hold.checkout_hold_token)]).then(([data,couponState])=>{if(!active)return;setContext(data);setCustomerBound(data.customer_bound);setCoupon(couponState);setCouponCode(couponState.coupon_code??'');setPriceConfirmed(data.customer_bound)}).catch(cause=>active&&setError(readableError(cause))).finally(()=>active&&setLoading(false));return()=>{active=false}},[hold.checkout_hold_token])
  const requiredAnswersReady=useMemo(()=>{if(!context)return false;return context.fields.filter(f=>f.is_required).every(f=>{const value=answers[f.id];if(f.field_type==='BOOLEAN')return value===true||value===false;return value!==null&&value!==undefined&&String(value).trim()!==''})},[answers,context])
  const termsReady=useMemo(()=>!context?.service.requires_terms?true:context.terms.length>0&&context.terms.every(term=>acceptedTerms[term.id]),[acceptedTerms,context])
  const displayedTotal=numeric(coupon?.commercial_value??context?.summary.commercial_value);const displayedSubtotal=numeric(coupon?.subtotal??context?.summary.commercial_value);const displayedDiscount=numeric(coupon?.coupon_discount)
  async function applyCoupon(){setCouponBusy(true);setError(null);try{const state=await applyCheckoutCoupon(hold.checkout_hold_token,couponCode);setCoupon(state);setCouponCode(state.coupon_code??couponCode)}catch(cause){setError(readableError(cause))}finally{setCouponBusy(false)}}
  async function removeCoupon(){setCouponBusy(true);setError(null);try{const state=await clearCheckoutCoupon(hold.checkout_hold_token);setCoupon(state);setCouponCode('')}catch(cause){setError(readableError(cause))}finally{setCouponBusy(false)}}
  async function saveCustomer(){if(!context)return;setBinding(true);setError(null);try{await bindCheckoutCustomer({token:hold.checkout_hold_token,name,email,phone,taxId});setCustomerBound(true);setPackages(await listCheckoutPackages(hold.checkout_hold_token))}catch(cause){setError(readableError(cause))}finally{setBinding(false)}}
  async function choosePackage(nextId:string){setPackageBusy(true);setError(null);try{if(nextId)await selectCheckoutPackage(hold.checkout_hold_token,nextId);else await clearCheckoutPackage(hold.checkout_hold_token);setPackageId(nextId)}catch(cause){setError(readableError(cause))}finally{setPackageBusy(false)}}
  async function submit(){if(!context||!customerBound||!requiredAnswersReady||!termsReady)return;setSubmitting(true);setError(null);try{const payloadAnswers:ServiceAnswer[]=context.fields.filter(f=>answers[f.id]!==undefined&&answers[f.id]!==null&&answers[f.id]!=='').map(f=>({service_field_id:f.id,value:answers[f.id]??null}));const appointment=await submitBookingCheckout({token:hold.checkout_hold_token,termVersionIds:context.terms.filter(t=>acceptedTerms[t.id]).map(t=>t.id),answers:payloadAnswers}) as CheckoutResult;setResult(appointment);sessionStorage.removeItem('bs_checkout_hold');if(appointment.pre_reservation){sessionStorage.removeItem('bs_appointment_manage')}else{sessionStorage.setItem('bs_appointment_manage',JSON.stringify({appointmentId:appointment.appointment_id,publicCode:appointment.public_code,accessToken:appointment.access_token,status:appointment.status}))}}catch(cause){setError(readableError(cause))}finally{setSubmitting(false)}}
  if(loading)return <section className="checkout-panel"><p>Preparando sua reserva…</p></section>;if(!context)return <section className="checkout-panel"><div className="form-alert error">{error??'Checkout indisponível.'}</div></section>
  if(result?.pre_reservation)return <section className="checkout-panel checkout-result" aria-live="polite"><small>Pré-reserva criada</small><h2>{context.service.name}</h2><p>Código: <strong>{result.public_code}</strong></p><p>Seu horário está reservado temporariamente até <strong>{deadline(result.pre_reservation_expires_at)}</strong>.</p><p>Enviamos para seu e-mail o link seguro de pagamento. A reserva só será confirmada quando o pagamento for aprovado dentro desse prazo.</p>{result.pre_reservation_email_sent===false?<div className="form-alert error">A pré-reserva foi criada, mas não conseguimos confirmar o envio do e-mail. Entre em contato com a equipe antes do vencimento.</div>:null}<p>Sem pagamento aprovado até o vencimento, a pré-reserva expira automaticamente e o horário volta a ficar disponível.</p></section>
  if(result)return <section className="checkout-panel checkout-result" aria-live="polite"><small>{result.status==='CONFIRMED'?'Reserva confirmada':'Falta só o pagamento'}</small><h2>{context.service.name}</h2><p>Código da reserva: <strong>{result.public_code}</strong></p>{result.status==='CONFIRMED'?<p>Seu pacote cobriu a reserva e não há pagamento pendente.</p>:<p>Para confirmar sua reserva, falta pagar <strong>{money.format(numeric(result.cash_due))}</strong>.</p>}</section>
  return <section className="checkout-panel"><div className="checkout-heading"><small>Seu horário está reservado</small><h2>Complete sua reserva</h2><p>Conclua antes do tempo indicado para manter este horário.</p></div>{error?<div className="form-alert error" role="alert">{error}</div>:null}
    {!priceConfirmed?<div className="checkout-section checkout-confirmation"><h3>Confirme sua reserva</h3><div className="checkout-price-summary"><div><span>Serviço</span><strong>{context.service.name}</strong></div><div><span>Subtotal</span><strong>{money.format(displayedSubtotal)}</strong></div>{displayedDiscount>0?<div className="checkout-discount"><span>Cupom {coupon?.coupon_code}</span><strong>− {money.format(displayedDiscount)}</strong></div>:null}<div className="checkout-total"><span>Valor total</span><strong>{money.format(displayedTotal)}</strong></div></div><div className="checkout-coupon-row"><label><span>Cupom de desconto</span><input value={couponCode} onChange={e=>setCouponCode(e.target.value.toUpperCase())} placeholder="Digite seu cupom" disabled={couponBusy}/></label>{coupon?.coupon_code?<button className="secondary" type="button" disabled={couponBusy} onClick={()=>void removeCoupon()}>{couponBusy?'Aguarde…':'Remover'}</button>:<button className="secondary" type="button" disabled={couponBusy||couponCode.trim().length<3} onClick={()=>void applyCoupon()}>{couponBusy?'Aplicando…':'Aplicar cupom'}</button>}</div><button className="primary" type="button" disabled={couponBusy} onClick={()=>setPriceConfirmed(true)}>Confirmar valor e continuar</button></div>:null}
    {priceConfirmed?<><div className="checkout-section"><div className="checkout-section-title"><h3>Seus dados</h3>{!customerBound?<button className="checkout-link" type="button" onClick={()=>setPriceConfirmed(false)}>Alterar cupom</button>:null}</div><div className="checkout-grid"><label>Nome completo *<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label><label>E-mail *<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>WhatsApp *<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" autoComplete="tel"/></label><label>CPF/CNPJ{context.require_tax_id?' *':''}<input value={taxId} onChange={e=>setTaxId(e.target.value)} inputMode="numeric"/></label></div>{!customerBound?<button className="primary" type="button" disabled={binding||digits(phone).length<10} onClick={()=>void saveCustomer()}>{binding?'Salvando…':'Continuar'}</button>:<div className="form-alert success">Dados salvos. Você pode continuar.</div>}</div>
    {customerBound&&packages.length>0?<div className="checkout-section"><h3>Pacote de horas</h3><p>Se quiser, use um pacote elegível nesta reserva.</p><div className="package-list"><label className={`package-option ${packageId===''?'selected':''}`}><input type="radio" name="hour-package" checked={packageId===''} disabled={packageBusy} onChange={()=>void choosePackage('')}/><span><strong>Não usar pacote</strong><small>Seguir com pagamento normal.</small></span></label>{packages.map(item=><label className={`package-option ${packageId===item.hour_package_id?'selected':''} ${!item.usable?'disabled':''}`} key={item.hour_package_id}><input type="radio" name="hour-package" checked={packageId===item.hour_package_id} disabled={packageBusy||!item.usable} onChange={()=>void choosePackage(item.hour_package_id)}/><span><strong>{item.name}</strong><small>Saldo disponível: {Math.floor(item.available_seconds/3600)}h {Math.floor((item.available_seconds%3600)/60)}min · Esta reserva utiliza: {Math.floor(item.charged_seconds/60)} min</small>{numeric(item.cash_due)>0?<small>Adicionais a pagar: {money.format(numeric(item.cash_due))}</small>:null}</span></label>)}</div></div>:null}
    {customerBound&&context.fields.length>0?<div className="checkout-section"><h3>Informações para sua reserva</h3><div className="checkout-grid">{context.fields.map(field=><FieldInput key={field.id} field={field} value={answers[field.id]} onChange={value=>setAnswers(current=>({...current,[field.id]:value}))}/>)}</div></div>:null}
    {customerBound&&context.terms.length>0?<div className="checkout-section"><h3>Termos</h3><div className="terms-list">{context.terms.map(term=><div className="term-card" key={term.id}><details><summary>{term.name}</summary><div className="term-content">{term.content}</div></details><label className="checkout-checkbox"><input type="checkbox" checked={acceptedTerms[term.id]??false} onChange={e=>setAcceptedTerms(current=>({...current,[term.id]:e.target.checked}))}/><span>Li e aceito este termo.</span></label></div>)}</div></div>:null}
    {customerBound?<div className="checkout-submit-row"><div><small>Valor total</small><strong>{money.format(displayedTotal)}</strong>{displayedDiscount>0?<span>Economia de {money.format(displayedDiscount)} com {coupon?.coupon_code}</span>:null}</div><button className="primary" type="button" disabled={submitting||packageBusy||!requiredAnswersReady||!termsReady} onClick={()=>void submit()}>{submitting?'Concluindo…':packageId?'Confirmar e continuar':'Concluir reserva'}</button></div>:null}</>:null}
  </section>
}
