import { FormEvent, useEffect, useMemo, useState } from 'react'
import { createCoupon, loadCoupons, removeCoupon, updateCoupon, type CouponAdminRow, type CouponCustomerOption, type CouponServiceOption } from './couponAdminApi'
import { supabase } from './supabase'

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })
function num(value: unknown) { const n = Number(value ?? 0); return Number.isFinite(n) ? n : 0 }
function localInput(value: string | null) { if (!value) return ''; const date = new Date(value); const shifted = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return shifted.toISOString().slice(0, 16) }
function isoOrNull(value: string) { return value ? new Date(value).toISOString() : null }

function Login({ onReady }: { onReady: (token: string) => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('')
  async function submit(e: FormEvent) { e.preventDefault(); const { data, error: authError } = await supabase.auth.signInWithPassword({ email, password }); if (authError || !data.session) return setError('Não foi possível entrar.'); onReady(data.session.access_token) }
  return <main className="admin-shell login-shell"><form className="login-card" onSubmit={submit}><h1>BlackSheep Agenda</h1><p>Gestão de cupons</p><label><span>E-mail</span><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label><span>Senha</span><input type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label>{error ? <div className="form-alert error">{error}</div> : null}<button className="primary">Entrar</button></form></main>
}

type Draft = Omit<CouponAdminRow, 'status' | 'source' | 'source_appointment_id' | 'customer_name'> & { valid_from_input: string; valid_until_input: string }
function fromCoupon(row: CouponAdminRow): Draft { return { id: row.id, code: row.code, discount_type: row.discount_type, discount_value: row.discount_value, valid_from: row.valid_from, valid_until: row.valid_until, valid_from_input: localInput(row.valid_from), valid_until_input: localInput(row.valid_until), is_active: row.is_active, customer_id: row.customer_id, max_uses: row.max_uses, max_uses_per_customer: row.max_uses_per_customer, used_count: row.used_count, service_ids: [...row.service_ids] } }
function blankDraft(): Draft { return { id: '', code: '', discount_type: 'PERCENT', discount_value: 10, valid_from: null, valid_until: null, valid_from_input: '', valid_until_input: '', is_active: true, customer_id: null, max_uses: null, max_uses_per_customer: 1, used_count: 0, service_ids: [] } }

export function CouponAdmin() {
  const [authReady, setAuthReady] = useState(false); const [token, setToken] = useState<string | null>(null)
  const [coupons, setCoupons] = useState<CouponAdminRow[]>([]); const [services, setServices] = useState<CouponServiceOption[]>([]); const [customers, setCustomers] = useState<CouponCustomerOption[]>([])
  const [selectedId, setSelectedId] = useState(''); const [draft, setDraft] = useState<Draft>(blankDraft()); const [creating, setCreating] = useState(false)
  const [operationFilter, setOperationFilter] = useState<'ALL' | 'SABRINA' | 'BLACKSHEEP'>('ALL'); const [customerSearch, setCustomerSearch] = useState('')
  const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('')

  useEffect(() => { supabase.auth.getSession().then(({ data }) => { setToken(data.session?.access_token ?? null); setAuthReady(true) }); const { data } = supabase.auth.onAuthStateChange((_e, session) => { setToken(session?.access_token ?? null); setAuthReady(true) }); return () => data.subscription.unsubscribe() }, [])
  async function load(preferred?: string) { if (!token) return; try { const bundle = await loadCoupons(token); setCoupons(bundle.coupons); setServices(bundle.services); setCustomers(bundle.customers); const id = preferred && bundle.coupons.some((c) => c.id === preferred) ? preferred : selectedId && bundle.coupons.some((c) => c.id === selectedId) ? selectedId : bundle.coupons[0]?.id ?? ''; setSelectedId(id); const current = bundle.coupons.find((c) => c.id === id); if (current) { setDraft(fromCoupon(current)); setCreating(false) } } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível carregar cupons.') } }
  useEffect(() => { if (token) void load() }, [token])
  const visibleServices = useMemo(() => services.filter((s) => s.is_active && (operationFilter === 'ALL' || s.operation_scope === operationFilter)), [services, operationFilter])
  const customerOptions = useMemo(() => { const q = customerSearch.trim().toLowerCase(); if (!q) return customers.slice(0, 30); return customers.filter((c) => `${c.name} ${c.email ?? ''}`.toLowerCase().includes(q)).slice(0, 30) }, [customers, customerSearch])
  function select(id: string) { const current = coupons.find((c) => c.id === id); if (!current) return; setSelectedId(id); setDraft(fromCoupon(current)); setCreating(false); setError(''); setMessage('') }
  function patch(values: Partial<Draft>) { setDraft((current) => ({ ...current, ...values })) }
  async function save() { if (!token) return; setSaving(true); setError(''); setMessage(''); try { const payload = { code: draft.code.trim().toUpperCase(), discount_type: draft.discount_type, discount_value: num(draft.discount_value), valid_from: isoOrNull(draft.valid_from_input), valid_until: isoOrNull(draft.valid_until_input), max_uses: draft.max_uses, max_uses_per_customer: draft.max_uses_per_customer, customer_id: draft.customer_id, service_ids: draft.service_ids }; if (creating) { await createCoupon(payload, token); setMessage('Cupom criado.') } else { await updateCoupon({ ...payload, coupon_id: draft.id, is_active: draft.is_active }, token); setMessage('Cupom atualizado.') } await load(draft.id || undefined) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível salvar.') } finally { setSaving(false) } }
  async function remove() { if (!token || !draft.id) return; setSaving(true); setError(''); try { const result = await removeCoupon(draft.id, token); setMessage(result.archived ? 'Cupom já usado: foi arquivado.' : 'Cupom excluído.'); setSelectedId(''); setDraft(blankDraft()); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível remover.') } finally { setSaving(false) } }

  if (!authReady) return <main className="admin-shell"><p>Carregando acesso.</p></main>
  if (!token) return <Login onReady={setToken} />
  return <main className="admin-shell settings-shell">
    <header className="admin-title-row settings-header"><div><span className="agenda-eyebrow">Financeiro</span><h1>Cupons</h1><p>Criação, validade, escopo e limites de uso globais e por cliente.</p></div><div className="agenda-header-actions"><a className="secondary agenda-link-button" href="/admin/catalogo">Catálogo</a><a className="secondary agenda-link-button" href="/admin/agenda">Agenda</a></div></header>
    {error ? <div className="form-alert error">{error}</div> : null}{message ? <div className="form-alert success">{message}</div> : null}
    <div className="coupon-layout"><aside className="settings-service-list"><div className="settings-card-heading"><h2>Cupons</h2><button className="secondary" type="button" onClick={() => { setCreating(true); setSelectedId(''); setDraft(blankDraft()) }}>+ Novo</button></div>{coupons.map((coupon) => <button key={coupon.id} className={coupon.id === selectedId ? 'active' : ''} onClick={() => select(coupon.id)}><strong>{coupon.code}</strong><span>{coupon.discount_type === 'PERCENT' ? `${coupon.discount_value}%` : money.format(num(coupon.discount_value))} • {coupon.status}</span><small>{coupon.used_count}{coupon.max_uses ? ` / ${coupon.max_uses}` : ''} uso(s)</small></button>)}</aside>
      <div className="settings-editor"><section className="settings-card"><div className="settings-card-heading"><div><h2>{creating ? 'Novo cupom' : draft.code || 'Cupom'}</h2><p>O contador de usos é somente leitura.</p></div>{!creating ? <span className="agenda-badge">{coupons.find((c) => c.id === draft.id)?.status ?? '—'}</span> : null}</div>
        <div className="settings-field-grid"><label><span>Código</span><input value={draft.code} onChange={(e) => patch({ code: e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g, '') })} /></label><label><span>Tipo de desconto</span><select value={draft.discount_type} onChange={(e) => patch({ discount_type: e.target.value as 'FIXED' | 'PERCENT' })}><option value="PERCENT">Percentual</option><option value="FIXED">Valor fixo</option></select></label><label><span>{draft.discount_type === 'PERCENT' ? 'Desconto (%)' : 'Desconto (R$)'}</span><input type="number" min="0.01" step="0.01" value={num(draft.discount_value)} onChange={(e) => patch({ discount_value: Number(e.target.value) })} /></label><label><span>Usos realizados</span><input disabled value={draft.used_count} /></label><label><span>Válido a partir de</span><input type="datetime-local" value={draft.valid_from_input} onChange={(e) => patch({ valid_from_input: e.target.value })} /></label><label><span>Válido até</span><input type="datetime-local" value={draft.valid_until_input} onChange={(e) => patch({ valid_until_input: e.target.value })} /></label><label><span>Uso máximo total</span><input type="number" min="1" placeholder="Sem limite" value={draft.max_uses ?? ''} onChange={(e) => patch({ max_uses: e.target.value ? Number(e.target.value) : null })} /></label><label><span>Uso máximo por cliente</span><input type="number" min="1" placeholder="Sem limite" value={draft.max_uses_per_customer ?? ''} onChange={(e) => patch({ max_uses_per_customer: e.target.value ? Number(e.target.value) : null })} /></label>{!creating ? <label className="settings-check"><input type="checkbox" checked={draft.is_active} onChange={(e) => patch({ is_active: e.target.checked })} />Cupom ativo</label> : null}</div>
      </section>
      <section className="settings-card"><div className="settings-card-heading"><div><h2>Cliente específico</h2><p>Deixe vazio para qualquer cliente. O limite por cliente continua valendo individualmente.</p></div></div><input className="coupon-search" placeholder="Buscar nome ou e-mail" value={customerSearch} onChange={(e) => setCustomerSearch(e.target.value)} /><select value={draft.customer_id ?? ''} onChange={(e) => patch({ customer_id: e.target.value || null })}><option value="">Qualquer cliente</option>{customerOptions.map((c) => <option key={c.id} value={c.id}>{c.name}{c.email ? ` — ${c.email}` : ''}</option>)}</select></section>
      <section className="settings-card"><div className="settings-card-heading"><div><h2>Serviços válidos</h2><p>Nenhum marcado significa todos os serviços. Você pode filtrar por operação para selecionar.</p></div><select value={operationFilter} onChange={(e) => setOperationFilter(e.target.value as typeof operationFilter)}><option value="ALL">Todas</option><option value="SABRINA">Sabrina</option><option value="BLACKSHEEP">BlackSheep</option></select></div><div className="coupon-service-grid">{visibleServices.map((service) => <label key={service.id} className="coupon-service-option"><input type="checkbox" checked={draft.service_ids.includes(service.id)} onChange={(e) => patch({ service_ids: e.target.checked ? [...draft.service_ids, service.id] : draft.service_ids.filter((id) => id !== service.id) })} /><span><strong>{service.name}</strong><small>{service.operation_scope} • {service.category_name ?? 'Sem categoria'}</small></span></label>)}</div></section>
      <div className="catalog-actions"><button className="primary" disabled={saving} onClick={() => void save()}>{saving ? 'Salvando…' : creating ? 'Criar cupom' : 'Salvar cupom'}</button>{!creating ? <button className="danger-text" disabled={saving} onClick={() => void remove()}>Excluir / arquivar</button> : null}</div>
      </div></div>
  </main>
}
