import { FormEvent, useCallback, useEffect, useState } from 'react'
import { functionsBaseUrl, publicApiKey, supabase } from './supabase'

type Terms = { can_prebook:boolean; prebook_hold_minutes:number; max_active_prebooks:number; requires_manual_confirmation:boolean; billing_mode:'CHECKOUT'|'INVOICE'; invoice_due_days:number|null; is_active:boolean }
type Customer = { id:string; customer_type:string; name:string; legal_name:string|null; cpf_cnpj:string|null; email:string|null; phone:string|null; commercial_terms:Terms|null }
type Profile = { customer: Customer & { notes?:string|null }; terms:Terms|null; authorized_services:Array<{id:string;name:string;slug:string}>; active_pre_reservations:Array<{id:string;service_name:string;start_at:string;expires_at:string;status:string}> }
type Service = { id:string;name:string;slug:string;operation_scope:string }

async function api<T>(token:string, path:string, init?:RequestInit):Promise<T>{
  const response=await fetch(`${functionsBaseUrl}/admin-customers${path}`,{...init,headers:{apikey:publicApiKey,authorization:`Bearer ${token}`,'content-type':'application/json',...(init?.headers??{})}})
  const body=await response.json().catch(()=>({})); if(!response.ok)throw new Error(body?.error?.code??`HTTP_${response.status}`); return body as T
}

function defaultTerms():Terms{return{can_prebook:false,prebook_hold_minutes:1440,max_active_prebooks:1,requires_manual_confirmation:true,billing_mode:'CHECKOUT',invoice_due_days:null,is_active:true}}
function message(error:unknown){const code=error instanceof Error?error.message:'';if(code==='ADMIN_FINANCE_PERMISSION_REQUIRED')return'Alterar faturamento exige permissão financeira.';if(code==='ADMIN_PERMISSION_DENIED')return'Sua sessão não possui permissão para esta ação.';return`Não foi possível concluir a operação${code?` (${code})`:''}.`}

export function CustomerAdmin(){
  const[ready,setReady]=useState(false),[token,setToken]=useState<string|null>(null),[search,setSearch]=useState(''),[customers,setCustomers]=useState<Customer[]>([]),[selected,setSelected]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[services,setServices]=useState<Service[]>([]),[terms,setTerms]=useState<Terms>(defaultTerms()),[authorized,setAuthorized]=useState<string[]>([]),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setToken(data.session?.access_token??null);setReady(true)});const{data:l}=supabase.auth.onAuthStateChange((_e,s)=>{setToken(s?.access_token??null);setReady(true)});return()=>l.subscription.unsubscribe()},[])
  const list=useCallback(async(accessToken:string,q='')=>{setLoading(true);setError('');try{const r=await api<{customers:Customer[]}>(accessToken,`?search=${encodeURIComponent(q)}&limit=100`);setCustomers(r.customers??[])}catch(e){setError(message(e))}finally{setLoading(false)}},[])
  useEffect(()=>{if(token)void list(token)},[token,list])
  async function open(id:string){if(!token)return;setSelected(id);setLoading(true);setError('');setNotice('');try{const r=await api<{profile:Profile;services:Service[]}>(token,`?customer_id=${encodeURIComponent(id)}`);setProfile(r.profile);setServices(r.services??[]);setTerms(r.profile.terms?{...r.profile.terms}:defaultTerms());setAuthorized((r.profile.authorized_services??[]).map(s=>s.id))}catch(e){setError(message(e))}finally{setLoading(false)}}
  async function find(e?:FormEvent){e?.preventDefault();if(token)await list(token,search)}
  async function save(){if(!token||!profile)return;setSaving(true);setError('');setNotice('');try{const r=await api<{profile:Profile}>(token,'',{method:'PUT',body:JSON.stringify({customer_id:profile.customer.id,...terms,authorized_service_ids:authorized})});setProfile(r.profile);setTerms(r.profile.terms?{...r.profile.terms}:defaultTerms());setAuthorized((r.profile.authorized_services??[]).map(s=>s.id));setNotice('Condições comerciais salvas e auditadas. O cadastro mestre e o histórico de reservas não foram reescritos.');await list(token,search)}catch(e){setError(message(e))}finally{setSaving(false)}}
  if(!ready)return <main className="admin-shell"><p>Carregando acesso.</p></main>;if(!token)return <main className="admin-shell"><h1>Clientes</h1><p>Entre pela Gestão para acessar esta área.</p><a href="/admin">Voltar ao login</a></main>
  return <main className="admin-shell settings-shell"><header className="admin-title-row settings-header"><div><span className="agenda-eyebrow">BlackSheep Agenda</span><h1>Clientes</h1><p>Consulta do cadastro mestre e gestão das condições comerciais autorizadas. Dados históricos de reservas permanecem imutáveis.</p></div><div className="agenda-header-actions"><a className="secondary agenda-link-button" href="/admin/agenda">Agenda</a><a className="secondary agenda-link-button" href="/admin/pagamentos">Pagamentos</a></div></header>
  {error?<div className="form-alert error">{error}</div>:null}{notice?<div className="form-alert success">{notice}</div>:null}
  <div className="settings-layout"><aside className="settings-service-list"><form onSubmit={find}><label><span>Buscar cliente</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome, e-mail, telefone ou CPF/CNPJ"/></label><button className="secondary" disabled={loading}>Buscar</button></form>{customers.map(c=><button type="button" key={c.id} className={selected===c.id?'active':''} onClick={()=>void open(c.id)}><strong>{c.name}</strong><span>{c.email??c.phone??'Sem contato'}</span><small>{c.commercial_terms?.can_prebook?'Pré-reserva liberada':'Fluxo padrão'}</small></button>)}</aside>
  <div className="settings-editor">{profile?<><section className="settings-card"><h2>Cadastro mestre</h2><p>Somente leitura nesta fase: alterações comerciais não reescrevem identidade nem snapshots históricos.</p><div className="settings-field-grid"><label><span>Nome</span><input disabled value={profile.customer.name}/></label><label><span>Tipo</span><input disabled value={profile.customer.customer_type}/></label><label><span>Razão social</span><input disabled value={profile.customer.legal_name??''}/></label><label><span>CPF/CNPJ</span><input disabled value={profile.customer.cpf_cnpj??''}/></label><label><span>E-mail</span><input disabled value={profile.customer.email??''}/></label><label><span>Telefone</span><input disabled value={profile.customer.phone??''}/></label></div></section>
  <section className="settings-card"><h2>Condições comerciais</h2><div className="settings-field-grid"><label className="settings-check"><input type="checkbox" checked={terms.is_active} onChange={e=>setTerms(t=>({...t,is_active:e.target.checked}))}/>Condições especiais ativas</label><label className="settings-check"><input type="checkbox" checked={terms.can_prebook} onChange={e=>setTerms(t=>({...t,can_prebook:e.target.checked}))}/>Pode fazer pré-reserva</label><label className="settings-check"><input type="checkbox" checked={terms.requires_manual_confirmation} onChange={e=>setTerms(t=>({...t,requires_manual_confirmation:e.target.checked}))}/>Exige confirmação manual</label><label><span>Hold da pré-reserva (min)</span><input type="number" min="1" value={terms.prebook_hold_minutes} onChange={e=>setTerms(t=>({...t,prebook_hold_minutes:Number(e.target.value)}))}/></label><label><span>Máximo de pré-reservas ativas</span><input type="number" min="1" value={terms.max_active_prebooks} onChange={e=>setTerms(t=>({...t,max_active_prebooks:Number(e.target.value)}))}/></label><label><span>Cobrança</span><select value={terms.billing_mode} onChange={e=>setTerms(t=>({...t,billing_mode:e.target.value as Terms['billing_mode'],invoice_due_days:e.target.value==='INVOICE'?(t.invoice_due_days??0):null}))}><option value="CHECKOUT">Checkout</option><option value="INVOICE">Faturamento</option></select></label>{terms.billing_mode==='INVOICE'?<label><span>Vencimento da fatura (dias)</span><input type="number" min="0" value={terms.invoice_due_days??0} onChange={e=>setTerms(t=>({...t,invoice_due_days:Number(e.target.value)}))}/></label>:null}</div><p>Alterar cobrança/faturamento exige permissão financeira no servidor.</p></section>
  <section className="settings-card"><h2>Serviços autorizados para pré-reserva</h2><p>Nenhum marcado significa nenhum serviço autorizado para esta condição especial.</p><div className="coupon-service-grid">{services.map(s=><label key={s.id} className="coupon-service-option"><input type="checkbox" checked={authorized.includes(s.id)} onChange={e=>setAuthorized(a=>e.target.checked?[...a,s.id]:a.filter(id=>id!==s.id))}/><span><strong>{s.name}</strong><small>{s.operation_scope}</small></span></label>)}</div></section>
  {profile.active_pre_reservations?.length?<section className="settings-card"><h2>Pré-reservas ativas</h2>{profile.active_pre_reservations.map(r=><p key={r.id}><strong>{r.service_name}</strong> • {new Date(r.start_at).toLocaleString('pt-BR')} • expira {new Date(r.expires_at).toLocaleString('pt-BR')}</p>)}</section>:null}
  <div className="settings-actions"><button className="primary" disabled={saving} onClick={()=>void save()}>{saving?'Salvando…':'Salvar condições comerciais'}</button></div></>:<section className="settings-card"><p>Selecione um cliente para consultar o cadastro e as condições comerciais.</p></section>}</div></div></main>
}
