import { FormEvent, useCallback, useEffect, useState } from 'react'
import { functionsBaseUrl, publicApiKey, supabase } from './supabase'

type Terms = { can_prebook:boolean; prebook_hold_minutes:number; max_active_prebooks:number; requires_manual_confirmation:boolean; billing_mode:'CHECKOUT'|'INVOICE'; invoice_due_days:number|null; is_active:boolean }
type Customer = { id:string; customer_type:string; name:string; legal_name:string|null; cpf_cnpj:string|null; email:string|null; phone:string|null; birth_date?:string|null; commercial_terms:Terms|null }
type Profile = { customer: Customer & { notes?:string|null }; terms:Terms|null; authorized_services:Array<{id:string;name:string;slug:string}>; active_pre_reservations:Array<{id:string;service_name:string;start_at:string;expires_at:string;status:string}> }
type Service = { id:string;name:string;slug:string;operation_scope:string }
type BirthDateCandidate = { appointment_answer_id:string; appointment_id:string; appointment_public_code:string|null; appointment_start_at:string|null; service_name:string|null; field_key_snapshot:string|null; label_snapshot:string|null; collected_birth_date:string; canonical_birth_date:string|null; matches_canonical:boolean; needs_reconciliation:boolean }
type BirthDateReconciliation = { canonical_birth_date:string|null; candidates:BirthDateCandidate[] }

async function api<T>(token:string, path:string, init?:RequestInit):Promise<T>{
  const response=await fetch(`${functionsBaseUrl}/admin-customers${path}`,{...init,headers:{apikey:publicApiKey,authorization:`Bearer ${token}`,'content-type':'application/json',...(init?.headers??{})}})
  const body=await response.json().catch(()=>({})); if(!response.ok)throw new Error(body?.error?.code??`HTTP_${response.status}`); return body as T
}

function defaultTerms():Terms{return{can_prebook:false,prebook_hold_minutes:2880,max_active_prebooks:1,requires_manual_confirmation:false,billing_mode:'CHECKOUT',invoice_due_days:null,is_active:true}}
function message(error:unknown){const code=error instanceof Error?error.message:'';if(code==='ADMIN_FINANCE_PERMISSION_REQUIRED')return'Alterar faturamento exige permissão financeira.';if(code==='ADMIN_PERMISSION_DENIED')return'Sua sessão não possui permissão para esta ação.';if(code==='PREBOOK_REQUIRES_CHECKOUT')return'Clientes habilitados para pré-reserva usam confirmação por pagamento no checkout.';if(code==='CUSTOMER_BIRTH_DATE_FUTURE')return'A data de nascimento não pode estar no futuro.';if(code==='CUSTOMER_BIRTH_DATE_PERSON_ONLY')return'Data de nascimento só pode ser definida para cliente pessoa.';if(code==='CUSTOMER_BIRTH_DATE_RECONCILIATION_QUERY_FAILED')return'Não foi possível consultar as datas coletadas nos serviços.';return`Não foi possível concluir a operação${code?` (${code})`:''}.`}
function formatDate(value:string|null){if(!value)return'Não informada';const [year,month,day]=value.split('-');return`${day}/${month}/${year}`}
function formatDateTime(value:string|null){return value?new Date(value).toLocaleString('pt-BR', { timeZone:'America/Sao_Paulo' }):'Data do atendimento indisponível'}

export function CustomerAdmin(){
  const[ready,setReady]=useState(false),[token,setToken]=useState<string|null>(null),[search,setSearch]=useState(''),[customers,setCustomers]=useState<Customer[]>([]),[selected,setSelected]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[services,setServices]=useState<Service[]>([]),[terms,setTerms]=useState<Terms>(defaultTerms()),[authorized,setAuthorized]=useState<string[]>([]),[birthDate,setBirthDate]=useState(''),[birthDateReconciliation,setBirthDateReconciliation]=useState<BirthDateReconciliation|null>(null),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[savingBirthDate,setSavingBirthDate]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setToken(data.session?.access_token??null);setReady(true)});const{data:l}=supabase.auth.onAuthStateChange((_e,s)=>{setToken(s?.access_token??null);setReady(true)});return()=>l.subscription.unsubscribe()},[])
  const list=useCallback(async(accessToken:string,q='')=>{setLoading(true);setError('');try{const r=await api<{customers:Customer[]}>(accessToken,`?search=${encodeURIComponent(q)}&limit=100`);setCustomers(r.customers??[])}catch(e){setError(message(e))}finally{setLoading(false)}},[])
  useEffect(()=>{if(token)void list(token)},[token,list])
  async function open(id:string){if(!token)return;setSelected(id);setLoading(true);setError('');setNotice('');try{const r=await api<{profile:Profile;services:Service[];birth_date_reconciliation:BirthDateReconciliation}>(token,`?customer_id=${encodeURIComponent(id)}`);setProfile(r.profile);setServices(r.services??[]);setTerms(r.profile.terms?{...r.profile.terms}:defaultTerms());setAuthorized((r.profile.authorized_services??[]).map(s=>s.id));setBirthDate(r.profile.customer.birth_date??'');setBirthDateReconciliation(r.birth_date_reconciliation??{canonical_birth_date:r.profile.customer.birth_date??null,candidates:[]})}catch(e){setError(message(e));setBirthDateReconciliation(null)}finally{setLoading(false)}}
  async function find(e?:FormEvent){e?.preventDefault();if(token)await list(token,search)}
  async function save(){if(!token||!profile)return;setSaving(true);setError('');setNotice('');try{const normalizedTerms=terms.can_prebook?{...terms,billing_mode:'CHECKOUT' as const,invoice_due_days:null,prebook_hold_minutes:2880,requires_manual_confirmation:false}:terms;const r=await api<{profile:Profile}>(token,'',{method:'PUT',body:JSON.stringify({customer_id:profile.customer.id,...normalizedTerms,authorized_service_ids:authorized})});setProfile(r.profile);setTerms(r.profile.terms?{...r.profile.terms}:defaultTerms());setAuthorized((r.profile.authorized_services??[]).map(s=>s.id));setNotice('Condições comerciais salvas e auditadas. O cadastro mestre e o histórico de reservas não foram reescritos.');await list(token,search)}catch(e){setError(message(e))}finally{setSaving(false)}}
  async function saveBirthDate(nextBirthDate=birthDate){if(!token||!profile)return;setSavingBirthDate(true);setError('');setNotice('');try{const r=await api<{profile:Profile}>(token,'',{method:'PUT',body:JSON.stringify({action:'birth_date',customer_id:profile.customer.id,birth_date:nextBirthDate||null})});const canonical=r.profile.customer.birth_date??null;setProfile(r.profile);setBirthDate(canonical??'');setBirthDateReconciliation(current=>current?{canonical_birth_date:canonical,candidates:current.candidates.map(candidate=>({...candidate,canonical_birth_date:canonical,matches_canonical:canonical!==null&&candidate.collected_birth_date===canonical,needs_reconciliation:canonical!==candidate.collected_birth_date}))}:current);setNotice('Data de nascimento canônica salva e auditada. Reservas e respostas históricas não foram alteradas.')}catch(e){setError(message(e))}finally{setSavingBirthDate(false)}}
  if(!ready)return <main className="admin-shell"><p>Carregando acesso.</p></main>;if(!token)return <main className="admin-shell"><h1>Clientes</h1><p>Entre pela Gestão para acessar esta área.</p><a href="/admin">Voltar ao login</a></main>
  return <main className="admin-shell settings-shell"><header className="admin-title-row settings-header"><div><span className="agenda-eyebrow">BlackSheep Agenda</span><h1>Clientes</h1><p>Consulta do cadastro mestre e gestão das condições comerciais autorizadas. Dados históricos de reservas permanecem imutáveis.</p></div><div className="agenda-header-actions"><a className="secondary agenda-link-button" href="/admin/agenda">Agenda</a><a className="secondary agenda-link-button" href="/admin/pagamentos">Pagamentos</a></div></header>
  {error?<div className="form-alert error">{error}</div>:null}{notice?<div className="form-alert success">{notice}</div>:null}
  <div className="settings-layout"><aside className="settings-service-list"><form onSubmit={find}><label><span>Buscar cliente</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome, e-mail, telefone ou CPF/CNPJ"/></label><button className="secondary" disabled={loading}>Buscar</button></form>{customers.map(c=><button type="button" key={c.id} className={selected===c.id?'active':''} onClick={()=>void open(c.id)}><strong>{c.name}</strong><span>{c.email??c.phone??'Sem contato'}</span><small>{c.commercial_terms?.can_prebook?'Pré-reserva liberada':'Fluxo padrão'}</small></button>)}</aside>
  <div className="settings-editor">{profile?<><section className="settings-card"><h2>Cadastro mestre</h2><p>Identidade permanece somente leitura. A data de nascimento é o único dado mestre editável aqui porque alimenta a automação de aniversário e possui mutation auditada própria.</p><div className="settings-field-grid"><label><span>Nome</span><input disabled value={profile.customer.name}/></label><label><span>Tipo</span><input disabled value={profile.customer.customer_type}/></label><label><span>Razão social</span><input disabled value={profile.customer.legal_name??''}/></label><label><span>CPF/CNPJ</span><input disabled value={profile.customer.cpf_cnpj??''}/></label><label><span>E-mail</span><input disabled value={profile.customer.email??''}/></label><label><span>Telefone</span><input disabled value={profile.customer.phone??''}/></label>{profile.customer.customer_type==='PERSON'?<label><span>Data de nascimento</span><input type="date" max={new Date().toISOString().slice(0,10)} value={birthDate} onChange={e=>setBirthDate(e.target.value)}/></label>:null}</div>{profile.customer.customer_type==='PERSON'?<div className="settings-actions"><button className="secondary" disabled={savingBirthDate} onClick={()=>void saveBirthDate()}>{savingBirthDate?'Salvando…':'Salvar data de nascimento'}</button></div>:null}</section>
  {profile.customer.customer_type==='PERSON'&&birthDateReconciliation?<section className="settings-card"><h2>Reconciliação de data de nascimento</h2><p>Data canônica atual: <strong>{formatDate(birthDateReconciliation.canonical_birth_date)}</strong>. Só aparecem abaixo valores capturados por campos explicitamente mapeados como data de nascimento; nenhum texto livre é interpretado.</p>{birthDateReconciliation.candidates.length===0?<p>Nenhuma data de nascimento semanticamente mapeada foi coletada em atendimentos deste cliente.</p>:birthDateReconciliation.candidates.map(candidate=><div key={candidate.appointment_answer_id} className="settings-card"><p><strong>{candidate.service_name??'Serviço'}</strong> • {candidate.appointment_public_code??candidate.appointment_id}</p><p>{formatDateTime(candidate.appointment_start_at)} • campo “{candidate.label_snapshot??candidate.field_key_snapshot??'Data de nascimento'}”</p><p>Coletada: <strong>{formatDate(candidate.collected_birth_date)}</strong> • Canônica: <strong>{formatDate(birthDateReconciliation.canonical_birth_date)}</strong></p>{candidate.needs_reconciliation?<div className="settings-actions"><button className="secondary" disabled={savingBirthDate} onClick={()=>void saveBirthDate(candidate.collected_birth_date)}>{savingBirthDate?'Salvando…':`Promover ${formatDate(candidate.collected_birth_date)} para o cadastro mestre`}</button></div>:<p><strong>Já coincide com o cadastro mestre.</strong></p>}</div>) }<p>A promoção é sempre explícita, usa a mutation auditada de clientes e não altera respostas históricas nem executa aniversário retroativamente.</p></section>:null}
  <section className="settings-card"><h2>Condições comerciais</h2><div className="settings-field-grid"><label className="settings-check"><input type="checkbox" checked={terms.is_active} onChange={e=>setTerms(t=>({...t,is_active:e.target.checked}))}/>Condições especiais ativas</label><label className="settings-check"><input type="checkbox" checked={terms.can_prebook} onChange={e=>setTerms(t=>({...t,can_prebook:e.target.checked,billing_mode:e.target.checked?'CHECKOUT':t.billing_mode,invoice_due_days:e.target.checked?null:t.invoice_due_days,prebook_hold_minutes:2880,requires_manual_confirmation:false}))}/>Pode fazer pré-reserva</label><label><span>Máximo de pré-reservas ativas</span><input type="number" min="1" value={terms.max_active_prebooks} onChange={e=>setTerms(t=>({...t,max_active_prebooks:Number(e.target.value)}))}/></label><label><span>Cobrança</span><select disabled={terms.can_prebook} value={terms.billing_mode} onChange={e=>setTerms(t=>({...t,billing_mode:e.target.value as Terms['billing_mode'],invoice_due_days:e.target.value==='INVOICE'?(t.invoice_due_days??0):null}))}><option value="CHECKOUT">Checkout</option><option value="INVOICE">Faturamento</option></select></label>{terms.billing_mode==='INVOICE'&&!terms.can_prebook?<label><span>Vencimento da fatura (dias)</span><input type="number" min="0" value={terms.invoice_due_days??0} onChange={e=>setTerms(t=>({...t,invoice_due_days:Number(e.target.value)}))}/></label>:null}</div><p><strong>Pré-reserva:</strong> prazo global de 48 horas. Não existe confirmação manual nem segundo prazo: somente pagamento aprovado confirma a reserva. Sem pagamento dentro do vencimento, o horário é liberado automaticamente.</p><p>Alterar cobrança/faturamento exige permissão financeira no servidor.</p></section>
  <section className="settings-card"><h2>Serviços autorizados para pré-reserva</h2><p>Nenhum marcado significa nenhum serviço autorizado para esta condição especial.</p><div className="coupon-service-grid">{services.map(s=><label key={s.id} className="coupon-service-option"><input type="checkbox" checked={authorized.includes(s.id)} onChange={e=>setAuthorized(a=>e.target.checked?[...a,s.id]:a.filter(id=>id!==s.id))}/><span><strong>{s.name}</strong><small>{s.operation_scope}</small></span></label>)}</div></section>
  {profile.active_pre_reservations?.length?<section className="settings-card"><h2>Pré-reservas ativas</h2>{profile.active_pre_reservations.map(r=><p key={r.id}><strong>{r.service_name}</strong> • {new Date(r.start_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} • expira {new Date(r.expires_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</p>)}</section>:null}
  <div className="settings-actions"><button className="primary" disabled={saving} onClick={()=>void save()}>{saving?'Salvando…':'Salvar condições comerciais'}</button></div></>:<section className="settings-card"><p>Selecione um cliente para consultar o cadastro e as condições comerciais.</p></section>}</div></div></main>
}
