import { FormEvent,useEffect,useMemo,useState } from 'react'
import { addEmployeeException,createEmployee,loadEmployees,removeEmployeeException,replaceEmployeeServices,replaceWorkHours,updateEmployee,type EmployeeAssignment,type EmployeeBundle,type EmployeeRow,type EmployeeWorkRule } from './employeeAdminApi'
import { supabase } from './supabase'

const weekdays=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb']
const localInput=(value:string)=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
type Draft={id:string;name:string;email:string;phone:string;notes:string;is_active:boolean;service_ids:string[]}
const blank=():Draft=>({id:'',name:'',email:'',phone:'',notes:'',is_active:true,service_ids:[]})
const fromEmployee=(e:EmployeeRow):Draft=>({id:e.id,name:e.name,email:e.email??'',phone:e.phone??'',notes:e.notes??'',is_active:e.is_active,service_ids:e.service_assignments.filter(a=>a.is_active).map(a=>a.service_id)})
function Login({onReady}:{onReady:(token:string)=>void}){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();const{data,error:a}=await supabase.auth.signInWithPassword({email,password});if(a||!data.session)return setError('Não foi possível entrar.');onReady(data.session.access_token)}return <main className="admin-shell login-shell"><form className="login-card" onSubmit={submit}><h1>BlackSheep Agenda</h1><p>Gestão de funcionários</p><label><span>E-mail</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label><span>Senha</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="form-alert error">{error}</div>}<button className="primary">Entrar</button></form></main>}

export function EmployeeAdmin(){
 const[ready,setReady]=useState(false);const[token,setToken]=useState<string|null>(null);const[bundle,setBundle]=useState<EmployeeBundle|null>(null);const[selected,setSelected]=useState('');const[draft,setDraft]=useState<Draft>(blank());const[creating,setCreating]=useState(false);const[assignmentId,setAssignmentId]=useState('');const[rules,setRules]=useState<EmployeeWorkRule[]>([]);const[exceptionType,setExceptionType]=useState<'BLOCK'|'OPEN'>('BLOCK');const[exceptionStart,setExceptionStart]=useState('');const[exceptionEnd,setExceptionEnd]=useState('');const[exceptionReason,setExceptionReason]=useState('');const[error,setError]=useState('');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false)
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setToken(data.session?.access_token??null);setReady(true)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>{setToken(s?.access_token??null);setReady(true)});return()=>data.subscription.unsubscribe()},[])
 const current=useMemo(()=>bundle?.employees.find(e=>e.id===selected)??null,[bundle,selected]);const assignment=useMemo(()=>current?.service_assignments.find(a=>a.service_employee_id===assignmentId)??null,[current,assignmentId])
 async function reload(preferred?:string){if(!token)return;try{const data=await loadEmployees(token);setBundle(data);const id=preferred&&data.employees.some(e=>e.id===preferred)?preferred:selected&&data.employees.some(e=>e.id===selected)?selected:data.employees[0]?.id??'';setSelected(id);const e=data.employees.find(x=>x.id===id);if(e){setDraft(fromEmployee(e));const a=e.service_assignments.find(x=>x.is_active)??e.service_assignments[0];setAssignmentId(a?.service_employee_id??'');setRules(a?.work_hours??[]);setCreating(false)}}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar funcionários.')}}
 useEffect(()=>{if(token)void reload()},[token])
 useEffect(()=>{setRules(assignment?.work_hours??[])},[assignmentId,assignment])
 function patch(p:Partial<Draft>){setDraft(d=>({...d,...p}))}
 async function saveEmployee(){if(!token)return;setBusy(true);setError('');try{if(creating){const row=await createEmployee({name:draft.name,email:draft.email,phone:draft.phone,notes:draft.notes},token) as EmployeeRow;await replaceEmployeeServices(row.id,draft.service_ids,token);setMessage('Funcionário criado.');await reload(row.id)}else{await updateEmployee({employee_id:draft.id,name:draft.name,email:draft.email,phone:draft.phone,notes:draft.notes,is_active:draft.is_active},token);await replaceEmployeeServices(draft.id,draft.service_ids,token);setMessage('Funcionário atualizado.');await reload(draft.id)}}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.')}finally{setBusy(false)}}
 async function saveRules(){if(!token||!assignmentId)return;setBusy(true);try{await replaceWorkHours(assignmentId,rules,token);setMessage('Horários atualizados.');await reload(draft.id)}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar horários.')}finally{setBusy(false)}}
 async function addException(){if(!token||!assignmentId||!exceptionStart||!exceptionEnd)return;setBusy(true);try{await addEmployeeException({service_employee_id:assignmentId,exception_type:exceptionType,start_at:new Date(exceptionStart).toISOString(),end_at:new Date(exceptionEnd).toISOString(),reason:exceptionReason},token);setExceptionStart('');setExceptionEnd('');setExceptionReason('');setMessage(exceptionType==='BLOCK'?'Folga/bloqueio criado.':'Abertura especial criada.');await reload(draft.id)}catch(e){setError(e instanceof Error?e.message:'Falha ao criar exceção.')}finally{setBusy(false)}}
 async function removeException(id:string){if(!token)return;await removeEmployeeException(id,token);await reload(draft.id)}
 function selectEmployee(e:EmployeeRow){setSelected(e.id);setDraft(fromEmployee(e));setCreating(false);const a=e.service_assignments.find(x=>x.is_active)??e.service_assignments[0];setAssignmentId(a?.service_employee_id??'');setRules(a?.work_hours??[])}
 if(!ready)return <main className="admin-shell">Carregando…</main>;if(!token)return <Login onReady={setToken}/>
 return <main className="admin-shell settings-shell"><header className="admin-title-row settings-header"><div><span className="agenda-eyebrow">Equipe</span><h1>Funcionários</h1><p>Serviços, horários de trabalho, folgas e calendários.</p></div><div className="agenda-header-actions"><a className="secondary agenda-link-button" href="/admin/catalogo">Catálogo</a><a className="secondary agenda-link-button" href="/admin/agenda">Agenda</a></div></header>{error&&<div className="form-alert error">{error}</div>}{message&&<div className="form-alert success">{message}</div>}<div className="employee-layout"><aside className="settings-service-list"><div className="settings-card-heading"><h2>Equipe</h2><button className="secondary" onClick={()=>{setCreating(true);setSelected('');setDraft(blank());setAssignmentId('');setRules([])}}>+ Novo</button></div>{bundle?.employees.map(e=><button key={e.id} className={e.id===selected?'active':''} onClick={()=>selectEmployee(e)}><strong>{e.name}</strong><span>{e.is_active?'Ativo':'Inativo'}</span></button>)}</aside><div className="settings-editor"><section className="settings-card"><h2>Dados do funcionário</h2><div className="settings-field-grid"><label><span>Nome</span><input value={draft.name} onChange={e=>patch({name:e.target.value})}/></label><label><span>E-mail</span><input type="email" value={draft.email} onChange={e=>patch({email:e.target.value})}/></label><label><span>Telefone</span><input value={draft.phone} onChange={e=>patch({phone:e.target.value})}/></label><label className="settings-check"><input type="checkbox" checked={draft.is_active} onChange={e=>patch({is_active:e.target.checked})}/>Ativo</label><label className="settings-field-full"><span>Observação interna</span><textarea value={draft.notes} onChange={e=>patch({notes:e.target.value})}/></label></div><h3>Serviços que realiza</h3><div className="employee-service-grid">{bundle?.services.filter(s=>s.is_active).map(s=><label key={s.id}><input type="checkbox" checked={draft.service_ids.includes(s.id)} onChange={e=>patch({service_ids:e.target.checked?[...draft.service_ids,s.id]:draft.service_ids.filter(id=>id!==s.id)})}/><span><strong>{s.name}</strong><small>{s.operation_scope} • {s.category_name??'Sem categoria'}</small></span></label>)}</div><div className="catalog-actions"><button className="primary" disabled={busy||!draft.name.trim()} onClick={()=>void saveEmployee()}>{busy?'Salvando…':creating?'Criar funcionário':'Salvar funcionário'}</button></div></section>
 {!creating&&current?<><section className="settings-card"><div className="settings-card-heading"><div><h2>Horário de trabalho</h2><p>Configure por serviço; mais de uma faixa no mesmo dia é permitida.</p></div><select value={assignmentId} onChange={e=>setAssignmentId(e.target.value)}>{current.service_assignments.filter(a=>a.is_active).map(a=><option key={a.service_employee_id} value={a.service_employee_id}>{a.service_name}</option>)}</select></div>{assignmentId?<><div className="work-rule-list">{rules.map((rule,i)=><div key={`${rule.id??'new'}-${i}`} className="work-rule"><select value={rule.weekday} onChange={e=>setRules(rs=>rs.map((r,n)=>n===i?{...r,weekday:Number(e.target.value)}:r))}>{weekdays.map((d,n)=><option key={d} value={n}>{d}</option>)}</select><input type="time" value={String(rule.start_local_time).slice(0,5)} onChange={e=>setRules(rs=>rs.map((r,n)=>n===i?{...r,start_local_time:e.target.value}:r))}/><span>até</span><input type="time" value={String(rule.end_local_time).slice(0,5)} onChange={e=>setRules(rs=>rs.map((r,n)=>n===i?{...r,end_local_time:e.target.value}:r))}/><button className="danger-text" onClick={()=>setRules(rs=>rs.filter((_r,n)=>n!==i))}>Remover</button></div>)}</div><div className="catalog-actions"><button className="secondary" onClick={()=>setRules(rs=>[...rs,{weekday:1,start_local_time:'09:00',end_local_time:'18:00',slot_interval_minutes:30,is_active:true}])}>+ Faixa</button><button className="primary" disabled={busy} onClick={()=>void saveRules()}>Salvar horários</button></div></>:<p>Vincule um serviço para configurar horários.</p>}</section>
 <section className="settings-card"><h2>Folgas e dias especiais</h2>{assignment?<><div className="employee-exception-form"><select value={exceptionType} onChange={e=>setExceptionType(e.target.value as 'BLOCK'|'OPEN')}><option value="BLOCK">Folga / bloqueio</option><option value="OPEN">Abertura especial</option></select><input type="datetime-local" value={exceptionStart} onChange={e=>setExceptionStart(e.target.value)}/><input type="datetime-local" value={exceptionEnd} onChange={e=>setExceptionEnd(e.target.value)}/><input placeholder="Motivo" value={exceptionReason} onChange={e=>setExceptionReason(e.target.value)}/><button className="secondary" disabled={busy||!exceptionStart||!exceptionEnd} onClick={()=>void addException()}>Adicionar</button></div><div className="employee-exception-list">{assignment.exceptions.map(x=><div key={x.id}><span className={`agenda-badge ${x.exception_type==='BLOCK'?'agenda-badge-cancelled':'agenda-badge-confirmed'}`}>{x.exception_type==='BLOCK'?'Folga':'Abertura'}</span><strong>{new Date(x.start_at).toLocaleString('pt-BR')} → {new Date(x.end_at).toLocaleString('pt-BR')}</strong><span>{x.reason??''}</span><button className="danger-text" onClick={()=>void removeException(x.id)}>Excluir</button></div>)}</div></>:<p>Selecione um serviço.</p>}</section>
 <section className="settings-card"><h2>Calendário</h2>{assignment?.write_calendar?<p>Reservas deste serviço são escritas em <strong>{assignment.write_calendar.calendar_name}</strong> ({assignment.write_calendar.time_scope}).</p>:<p>Nenhum calendário de escrita configurado para este serviço.</p>}<p className="settings-hint">Conexão Google nunca é iniciada automaticamente. Mapeamentos só usam contas já conectadas.</p></section></>:null}</div></div></main>
}
